name: dice
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/dicee1.png
    - assets/dicee2.png
    - assets/dicee3.png
    - assets/dicee4.png
    - assets/dicee5.png
    - assets/dicee6.png
  fonts:
    - family: ProtestGuerrilla
      fonts:
        - asset: fonts/ProtestGuerrilla-Regular.ttf